# Generated by Django 5.1.3 on 2024-11-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_room_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
